"""PDF parser: text layer, pages, block splitting, and failure classification.

PDFs are generated by tests/support/pdf_fixtures.py from pypdf writer objects,
so each fixture's content sits next to its assertion and nothing binary or real
is committed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("pypdf", reason="pypdf is required for the PDF parser")

from document_processing.normalize import build_normalized_text  # noqa: E402
from document_processing.parsers import get_parser, parse_document  # noqa: E402
from document_processing.parsers.exceptions import (  # noqa: E402
    CorruptDocumentError,
    DocumentParseError,
    EmptyDocumentError,
    EncryptedDocumentError,
    OCRRequiredError,
)
from document_processing.parsers.pdf import PdfParser, split_blocks  # noqa: E402
from ingestion.chunker import chunk_document  # noqa: E402
from ingestion.config import IngestionConfig  # noqa: E402
from ingestion.tokenizers import SimpleTokenizer  # noqa: E402
from support.pdf_fixtures import write_image_only_pdf, write_text_pdf  # noqa: E402

TWO_PAGES = [
    [["첫째 쪽 제목"], ["첫째 쪽 본문은 예산 계획을 설명한다."]],
    [["둘째 쪽 전용 문구: 인건비 1억 2천만원."], ["Page two English line."]],
]


class TestRegistration:
    def test_the_registry_claims_pdf(self, tmp_path):
        path = write_text_pdf(tmp_path / "a.pdf", [[["본문."]]])
        assert isinstance(get_parser(path), PdfParser)


class TestTextExtraction:
    def test_a_single_page_is_extracted(self, tmp_path):
        parsed = parse_document(write_text_pdf(tmp_path / "a.pdf", [[["Hello text layer."]]]))
        assert [p.text for p in parsed.paragraphs] == ["Hello text layer."]
        assert parsed.file_type == "pdf"
        assert parsed.parser_name == "inhouse-pdf"
        assert parsed.page_count == 1

    def test_korean_text_survives_intact(self, tmp_path):
        body = "2026년도 사업계획서 — 예산 3억 원, 담당: 기획조정실."
        parsed = parse_document(write_text_pdf(tmp_path / "k.pdf", [[[body]]]))
        assert parsed.paragraphs[0].text == body
        assert body in build_normalized_text(parsed)

    def test_every_paragraph_carries_its_real_page(self, tmp_path):
        parsed = parse_document(write_text_pdf(tmp_path / "two.pdf", TWO_PAGES))
        def page_of(fragment: str) -> int | None:
            return next(p.page_number for p in parsed.paragraphs if fragment in p.text)

        # The heading has no final punctuation, so it shares a block with the
        # sentence after it -- by design. What matters is the page each is on.
        assert page_of("첫째 쪽 제목") == 1
        assert page_of("첫째 쪽 본문") == 1
        assert page_of("인건비 1억 2천만원") == 2
        assert page_of("Page two English line.") == 2
        assert {p.page_number for p in parsed.paragraphs} == {1, 2}
        assert parsed.page_count == 2

    def test_pdf_metadata_is_not_read_as_a_document_date(self, tmp_path):
        # A PDF's CreationDate is when the file was produced. The parser does
        # not surface it; dates come from the text, as for every format.
        parsed = parse_document(write_text_pdf(tmp_path / "m.pdf", [[["본문."]]]))
        assert not any("date" in key.lower() for key in parsed.metadata)


class TestBlockSplitting:
    def test_a_blank_line_divides_paragraphs(self):
        assert split_blocks("첫 문단 줄\n\n둘째 문단 줄") == ["첫 문단 줄", "둘째 문단 줄"]

    def test_a_sentence_ending_line_ends_a_block(self):
        text = "본 사업은 문서 검색을 개선한다. 담당은\n기획조정실이다.\n총 사업비는 3억 원이다.\n"
        assert split_blocks(text) == [
            "본 사업은 문서 검색을 개선한다. 담당은\n기획조정실이다.",
            "총 사업비는 3억 원이다.",
        ]

    def test_wrapped_lines_are_not_split_into_fragments(self):
        # One paragraph wrapped over five lines stays one block, not five.
        text = "이 문단은\n여러 줄에\n걸쳐\n줄바꿈되어\n추출되었다."
        assert len(split_blocks(text)) == 1

    def test_a_closing_quote_after_the_mark_still_ends_the_sentence(self):
        assert split_blocks('그는 "끝났다."\n다음 문단') == ['그는 "끝났다."', "다음 문단"]

    def test_blocks_stay_on_their_page_through_chunking(self, tmp_path):
        """Page provenance reaches the chunks, not only the parse.

        The budget is large enough to pack both pages into one chunk; the
        chunker must still split at the page boundary, or page-2 text would be
        cited as page 1.
        """
        parsed = parse_document(write_text_pdf(tmp_path / "two.pdf", TWO_PAGES))
        config = IngestionConfig(shared_root=tmp_path, chunk_target_tokens=512, chunk_max_tokens=512)
        chunks = chunk_document(parsed, SimpleTokenizer(), config)

        assert [c.page_number for c in chunks] == [1, 2]
        page_one, page_two = chunks
        assert "첫째 쪽 본문" in page_one.text and "둘째 쪽" not in page_one.text
        assert "인건비 1억 2천만원" in page_two.text and "첫째 쪽" not in page_two.text

    def test_formats_without_pages_still_pack_as_before(self, tmp_path):
        # The page-boundary rule must not change HWP/HWPX/DOCX chunking, whose
        # page_number is None throughout.
        from document_processing.models import ParsedDocument, ParsedParagraph

        doc = ParsedDocument(file_path="x.hwpx", file_type="hwpx", paragraphs=[
            ParsedParagraph(index=0, text="첫 문단."), ParsedParagraph(index=1, text="둘째 문단."),
        ])
        config = IngestionConfig(shared_root=tmp_path, chunk_target_tokens=512, chunk_max_tokens=512)
        chunks = chunk_document(doc, SimpleTokenizer(), config)
        assert len(chunks) == 1 and chunks[0].page_number is None


class TestNoTextLayer:
    def test_an_image_only_pdf_is_ocr_required_not_a_failure(self, tmp_path):
        with pytest.raises(OCRRequiredError) as caught:
            parse_document(write_image_only_pdf(tmp_path / "scan.pdf", pages=2))
        assert caught.value.error_code == "OCR_REQUIRED"

    def test_a_pdf_with_no_text_and_no_images_is_empty(self, tmp_path):
        with pytest.raises(EmptyDocumentError):
            parse_document(write_text_pdf(tmp_path / "blank.pdf", [[]]))


class TestFailures:
    def test_garbage_is_corrupt(self, tmp_path):
        path = tmp_path / "fake.pdf"
        path.write_bytes(b"this is not a pdf at all")
        with pytest.raises(CorruptDocumentError) as caught:
            parse_document(path)
        assert caught.value.error_code == "CORRUPT"

    def test_a_truncated_pdf_is_a_determination_not_a_crash(self, tmp_path):
        good = write_text_pdf(tmp_path / "good.pdf", TWO_PAGES).read_bytes()
        broken = tmp_path / "broken.pdf"
        broken.write_bytes(good[: len(good) // 3])
        with pytest.raises(DocumentParseError) as caught:
            parse_document(broken)
        assert caught.value.error_code in {"CORRUPT", "PARSE_FAILED"}

    def test_a_pdf_needing_a_password_is_encrypted(self, tmp_path):
        path = write_text_pdf(tmp_path / "locked.pdf", [[["비밀 본문."]]],
                              user_password="secret", owner_password="owner")
        with pytest.raises(EncryptedDocumentError) as caught:
            parse_document(path)
        assert caught.value.error_code == "ENCRYPTED"
        assert "비밀 본문" not in str(caught.value)

    def test_an_owner_password_only_pdf_is_read(self, tmp_path):
        # Restricts printing/copying but opens without a password.
        path = write_text_pdf(tmp_path / "restricted.pdf", [[["열람 가능한 본문."]]],
                              user_password="", owner_password="owner")
        assert parse_document(path).paragraphs[0].text == "열람 가능한 본문."

    def test_aes_without_a_crypto_library_is_encrypted_not_a_crash(self, tmp_path, monkeypatch):
        from pypdf import PdfReader
        from pypdf.errors import DependencyError

        path = write_text_pdf(tmp_path / "aes.pdf", [[["본문."]]],
                              user_password="", owner_password="owner")

        def needs_crypto(self, password):
            raise DependencyError("AES algorithm requires cryptography")

        monkeypatch.setattr(PdfReader, "decrypt", needs_crypto)
        with pytest.raises(EncryptedDocumentError) as caught:
            parse_document(path)
        assert caught.value.detail == "CRYPTO_LIBRARY_REQUIRED"
